# Generated by Django 3.2.18 on 2023-03-24 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20230322_2217'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
